
export const INGREDIENTS: object[] = [
  { name: 'Amber'},
  { name: 'Antlion Mandible'},
  { name:  'Armored Cavefish'},
  { name:  'Blinkroot'},
  { name:  'Bone'},
  { name:  'Bottle'},
  { name:  'Bottled Water'},
  { name:  'Cactus'},
  { name:  'Chaos Fish'},
  { name:  'Cobweb'},
  { name:  'Coral'},
  { name:  'Crimson Tigerfish'},
  { name:  'Crispy Honey Block'},
  { name:  'Crystal Shard'},
  { name:  'Damselfish'},
  { name:  'Daybloom'},
  { name:  'Deathweed'},
  { name:  'Double Cod'},
  { name:  'Ebonkoi'},
  { name:  'Fallen Star'},
  { name:  'Flarefin Koi'},
  { name:  'Feather'},
  { name:  'Fireblossom'},
  { name:  'Frost Minnow'},
  { name:  'Gel'},
  { name:  'Glowing Mushroom'},
  { name:  'Gold Ore'},
  { name:  'Greater Healing'},
  { name:  'Greater Mana'},
  { name:  'Hemopiranha'},
  { name:  'Iron Ore'},
  { name:  'Lens'},
  { name:  'Lesser Healing'},
  { name:  'Lesser Mana'},
  { name:  'Moonglow'},
  { name:  'Mushroom'},
  { name:  'Nebula Fragment'},
  { name:  'Obsidian'},
  { name:  'Obsidifish'},
  { name:  'Pink Gel'},
  { name:  'Pixie Dust'},
  { name:  'Princess Fish'},
  { name:  'Prismite'},
  { name:  'Rotten Chunk'},
  { name:  'Shark Fin'},
  { name:  'Shiverthorn'},
  { name:  'Solar Fragment'},
  { name:  'Specular Fish'},
  { name:  'Stardust Fragment'},
  { name:  'Stinger'},
  { name:  'Stinkfish'},
  { name:  'Unicorn Horn'},
  { name:  'Variegated Lardfish'},
  { name:  'Vortex Fragment'},
  { name:  'Waterleaf'},
  { name:  'Worm Tooth'}
];
